wandb_version: 1

logger:
  desc: null
  value:
    experiment_name: English_To_Swedish
    project: Translation
    entity: vitsiozo
model_settings:
  desc: null
  value:
    num_epochs: 10
    learning_rate: 0.001
    batch_size: 64
_wandb:
  desc: null
  value:
    python_version: 3.9.2
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715249975.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.2
      5: 0.16.6
      6: 4.40.2
      8:
      - 8
      13: darwin-x86_64
